CREATE TABLE `actions` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`from` VARCHAR(100) NOT NULL,
	`to` VARCHAR(100) NOT NULL,
	`valueFrom` VARCHAR(50) NOT NULL,
	`valueTo` VARCHAR(50) NOT NULL,
	`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
